#
# Makefile - Build PLL settings generator
#
# Developed by Werner Almesberger for Actility S.A., and
# licensed under LGPLv2 by Actility S.A.
#

CFLAGS = -Wall -O
LDLIBS = -lm

.PHONY:	all clean spotless

all:	pll

clean:

spotless:
	rm -f pll
